version: "3.9"

services: 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "9002:9000"
    expose:
      - 9002
    volumes:
      - ./api/.env:/usr/src/app/.env
    restart: on-failure
    working_dir: /usr/src/app
    networks:
      - default

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    volumes:
      - ./app/.env:/app/.env
    ports:
      - "3002:3000"
    expose:
      - 3002
    restart: on-failure
    networks:
      - default

  db:
    image: mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: taskmanager
      MYSQL_DATABASE: taskmanager
      MYSQL_ROOT_PASSWORD: taskmanager123
      MYSQL_PASSWORD: taskmanager123
    networks:
      - default

networks: 
  default:
    name: taskmanager