version: "3.9"

services: 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "9000:9000"
    expose:
      - 9000
    restart: on-failure
    working_dir: /usr/src/app
    networks:
      - default

  db:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: superplayer
      MYSQL_ROOT_PASSWORD: superplayer123
    networks:
      - default

networks: 
  default:
    name: superplayer